//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputSpeedExamination.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebService", ConfigurationName="ServiceReference.ClientServiceSoap")]
    public interface ClientServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/SayHello", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SayHello(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetAllDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetMajorByDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMajorByDepartment(string DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetUpdateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUpdateList();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetEdu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEdu(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserInfo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetClientIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetClientIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetExaminationGUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetExaminationGUID(string Number, string Department, string Major, string Class, string Name, string ContentMD5, string ContentTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/UpdateExaminationStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateExaminationStats(string GUID, string Stats, string Speed, string Process, string CorrectPercent);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetUpdateInterVal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetUpdateInterVal();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetBatchID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBatchID();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetAllContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllContent();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientServiceSoapChannel : InputSpeedExamination.ServiceReference.ClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceSoapClient : System.ServiceModel.ClientBase<InputSpeedExamination.ServiceReference.ClientServiceSoap>, InputSpeedExamination.ServiceReference.ClientServiceSoap {
        
        public ClientServiceSoapClient() {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string data) {
            return base.Channel.SayHello(data);
        }
        
        public System.Data.DataSet GetAllDepartment() {
            return base.Channel.GetAllDepartment();
        }
        
        public System.Data.DataSet GetMajorByDepartment(string DepartmentID) {
            return base.Channel.GetMajorByDepartment(DepartmentID);
        }
        
        public System.Data.DataSet GetUpdateList() {
            return base.Channel.GetUpdateList();
        }
        
        public string GetEdu(string username, string password) {
            return base.Channel.GetEdu(username, password);
        }
        
        public string GetUserInfo(string username, string password) {
            return base.Channel.GetUserInfo(username, password);
        }
        
        public string GetClientIP() {
            return base.Channel.GetClientIP();
        }
        
        public string GetExaminationGUID(string Number, string Department, string Major, string Class, string Name, string ContentMD5, string ContentTitle) {
            return base.Channel.GetExaminationGUID(Number, Department, Major, Class, Name, ContentMD5, ContentTitle);
        }
        
        public bool UpdateExaminationStats(string GUID, string Stats, string Speed, string Process, string CorrectPercent) {
            return base.Channel.UpdateExaminationStats(GUID, Stats, Speed, Process, CorrectPercent);
        }
        
        public int GetUpdateInterVal() {
            return base.Channel.GetUpdateInterVal();
        }
        
        public string GetBatchID() {
            return base.Channel.GetBatchID();
        }
        
        public System.Data.DataSet GetAllContent() {
            return base.Channel.GetAllContent();
        }
    }
}
