//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputSpeedExamination_Controller.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebService", ConfigurationName="ServiceReference.ControllerServiceSoap")]
    public interface ControllerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetStats", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStats(string BatchID, string RoomID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetExamRoomList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetExamRoomList(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/CreateNewExamRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewExamRoom(string RoomTitle, string IncludeIP, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/EditExamRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EditExamRoom(string RoomID, string RoomTitle, string IncludeIP, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/DeleteExamRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteExamRoom(string RoomID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetAllContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllContent(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/CreateNewContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewContent(string Title, string Content, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/UpdateContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateContent(string ContentID, string Title, string Content, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/DeleteContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteContent(string ContentID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetContentByPaperID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetContentByPaperID(string IncludePaper, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetContentByBatchID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetContentByBatchID(string BatchID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetBatchList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBatchList(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/CreateNewBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateNewBatch(string Title, string Remark, string IncludePaper, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/StartBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string StartBatch(string BatchID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/StopBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string StopBatch(string BatchID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/DeleteBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteBatch(string BatchID, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/EditBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EditBatch(string BatchID, string Title, string Remark, string IncludePaper, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControllerServiceSoapChannel : InputSpeedExamination_Controller.ServiceReference.ControllerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControllerServiceSoapClient : System.ServiceModel.ClientBase<InputSpeedExamination_Controller.ServiceReference.ControllerServiceSoap>, InputSpeedExamination_Controller.ServiceReference.ControllerServiceSoap {
        
        public ControllerServiceSoapClient() {
        }
        
        public ControllerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControllerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControllerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Data.DataSet GetStats(string BatchID, string RoomID, string username, string password) {
            return base.Channel.GetStats(BatchID, RoomID, username, password);
        }
        
        public System.Data.DataSet GetExamRoomList(string username, string password) {
            return base.Channel.GetExamRoomList(username, password);
        }
        
        public string CreateNewExamRoom(string RoomTitle, string IncludeIP, string username, string password) {
            return base.Channel.CreateNewExamRoom(RoomTitle, IncludeIP, username, password);
        }
        
        public string EditExamRoom(string RoomID, string RoomTitle, string IncludeIP, string username, string password) {
            return base.Channel.EditExamRoom(RoomID, RoomTitle, IncludeIP, username, password);
        }
        
        public bool DeleteExamRoom(string RoomID, string username, string password) {
            return base.Channel.DeleteExamRoom(RoomID, username, password);
        }
        
        public System.Data.DataSet GetAllContent(string username, string password) {
            return base.Channel.GetAllContent(username, password);
        }
        
        public string CreateNewContent(string Title, string Content, string username, string password) {
            return base.Channel.CreateNewContent(Title, Content, username, password);
        }
        
        public string UpdateContent(string ContentID, string Title, string Content, string username, string password) {
            return base.Channel.UpdateContent(ContentID, Title, Content, username, password);
        }
        
        public bool DeleteContent(string ContentID, string username, string password) {
            return base.Channel.DeleteContent(ContentID, username, password);
        }
        
        public System.Data.DataSet GetContentByPaperID(string IncludePaper, string username, string password) {
            return base.Channel.GetContentByPaperID(IncludePaper, username, password);
        }
        
        public System.Data.DataSet GetContentByBatchID(string BatchID, string username, string password) {
            return base.Channel.GetContentByBatchID(BatchID, username, password);
        }
        
        public System.Data.DataSet GetBatchList(string username, string password) {
            return base.Channel.GetBatchList(username, password);
        }
        
        public string CreateNewBatch(string Title, string Remark, string IncludePaper, string username, string password) {
            return base.Channel.CreateNewBatch(Title, Remark, IncludePaper, username, password);
        }
        
        public string StartBatch(string BatchID, string username, string password) {
            return base.Channel.StartBatch(BatchID, username, password);
        }
        
        public string StopBatch(string BatchID, string username, string password) {
            return base.Channel.StopBatch(BatchID, username, password);
        }
        
        public string DeleteBatch(string BatchID, string username, string password) {
            return base.Channel.DeleteBatch(BatchID, username, password);
        }
        
        public string EditBatch(string BatchID, string Title, string Remark, string IncludePaper, string username, string password) {
            return base.Channel.EditBatch(BatchID, Title, Remark, IncludePaper, username, password);
        }
    }
}
